'use strict';

// select score element
const score0El = document.getElementById('score--0');
const score1El = document.getElementById('score--1');
const current0El = document.getElementById('current--0');
const current1El = document.getElementById('current--1');
const diceEl = document.querySelector('.dice');
const btnNew = document.querySelector('.btn--new');
const btnRoll = document.querySelector('.btn--roll');
const btnHold = document.querySelector('.btn--hold');


// set the initial score of the players to 0
score0El.textContent = 0;
score1El.textContent = 0;
diceEl.classList.add('hidden');

// current score
let currentScore = 0;

// rolling dice functionality
btnRoll.addEventListener('click', function(){
    // 1. generate a random dice roll
    const dice = Math.trunc(Math.random() * 6) + 1;
    // console.log(dice);

    // 2. display dice
        //  first remove the hidden class
    diceEl.classList.remove('hidden');
        //  switch dice images attaching the random number generated by dice variable
    diceEl.src = `dice-${dice}.png`;
    
    // 3. check for rolled: 1 if true, switch to next player
    if(dice !== 1){
        // add this to current score
        currentScore += dice;
        current0El.textContent = currentScore; // CHANGE LATER
    }else{

    }

})